language: node_js
node_js:
  - "stable"
# Specify `npm install`
install:
  - npm install

# Continue to use the old cache location
cache:
  directories:
    - "node_modules"
script:
#  - npm test
  - npm run build
  - mv build/index.html build/200.html
deploy:
  provider: surge
  skip_cleanup: true
  domain: tabiri.surge.sh
  project: ./build/
on:
  branch: master