/* Country */
export const COUNTRIES_REQUESTING = 'COUNTRIES_REQUESTING';
export const COUNTRIES_REQUEST_SUCCESS = 'COUNTRIES_REQUEST_SUCCESS';
export const COUNTRIES_REQUEST_ERROR = 'COUNTRIES_REQUEST_ERROR';
export const RESET_COUNTRIES_REQUEST = 'RESET_COUNTRIES_REQUEST';

export const COUNTRY_REQUESTING = 'COUNTRY_REQUESTING';
export const COUNTRY_REQUEST_SUCCESS = 'COUNTRY_REQUEST_SUCCESS';
export const COUNTRY_REQUEST_ERROR = 'COUNTRY_REQUEST_ERROR';
export const RESET_COUNTRY_REQUEST = 'RESET_COUNTRY_REQUEST';

/* County */
export const COUNTIES_REQUESTING = 'COUNTIES_REQUESTING';
export const COUNTIES_REQUEST_SUCCESS = 'COUNTIES_REQUEST_SUCCESS';
export const COUNTIES_REQUEST_ERROR = 'COUNTIES_REQUEST_ERROR';
export const RESET_COUNTIES_REQUEST = 'RESET_COUNTIES_REQUEST';

export const COUNTY_REQUESTING = 'COUNTY_REQUESTING';
export const COUNTY_REQUEST_SUCCESS = 'COUNTY_REQUEST_SUCCESS';
export const COUNTY_REQUEST_ERROR = 'COUNTY_REQUEST_ERROR';
export const RESET_COUNTY_REQUEST = 'RESET_COUNTY_REQUEST';

/* Constituency */
export const CONSTITUENCIES_REQUESTING = 'CONSTITUENCIES_REQUESTING';
export const CONSTITUENCIES_REQUEST_SUCCESS = 'CONSTITUENCIES_REQUEST_SUCCESS';
export const CONSTITUENCIES_REQUEST_ERROR = 'CONSTITUENCIES_REQUEST_ERROR';
export const RESET_CONSTITUENCIES_REQUEST = 'RESET_CONSTITUENCIES_REQUEST';

export const CONSTITUENCY_REQUESTING = 'CONSTITUENCY_REQUESTING';
export const CONSTITUENCY_REQUEST_SUCCESS = 'CONSTITUENCY_REQUEST_SUCCESS';
export const CONSTITUENCY_REQUEST_ERROR = 'CONSTITUENCY_REQUEST_ERROR';
export const RESET_CONSTITUENCY_REQUEST = 'RESET_CONSTITUENCY_REQUEST';

/* Ward */
export const WARDS_REQUESTING = 'WARDS_REQUESTING';
export const WARDS_REQUEST_SUCCESS = 'WARDS_REQUEST_SUCCESS';
export const WARDS_REQUEST_ERROR = 'WARDS_REQUEST_ERROR';
export const RESET_WARDS_REQUEST = 'RESET_WARDS_REQUEST';

export const WARD_REQUESTING = 'WARD_REQUESTING';
export const WARD_REQUEST_SUCCESS = 'WARD_REQUEST_SUCCESS';
export const WARD_REQUEST_ERROR = 'WARD_REQUEST_ERROR';
export const RESET_WARD_REQUEST = 'RESET_WARD_REQUEST';

/* HealthFacility */
export const HEALTH_FACILITIES_REQUESTING = 'HEALTH_FACILITIES_REQUESTING';
export const HEALTH_FACILITIES_REQUEST_SUCCESS = 'HEALTH_FACILITIES_REQUEST_SUCCESS';
export const HEALTH_FACILITIES_REQUEST_ERROR = 'HEALTH_FACILITIES_REQUEST_ERROR';
export const RESET_HEALTH_FACILITIES_REQUEST = 'RESET_HEALTH_FACILITIES_REQUEST';

export const HEALTH_FACILITY_REQUESTING = 'HEALTH_FACILITY_REQUESTING';
export const HEALTH_FACILITY_REQUEST_SUCCESS = 'HEALTH_FACILITY_REQUEST_SUCCESS';
export const HEALTH_FACILITY_REQUEST_ERROR = 'HEALTH_FACILITY_REQUEST_ERROR';
export const RESET_HEALTH_FACILITY_REQUEST = 'RESET_HEALTH_FACILITY_REQUEST';
